services:
  openresty:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./examples/openresty/openresty-base.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./examples/openresty/monitorama-demo.conf:/etc/nginx/conf.d/default.conf
      - ./tmp/queue_count:/etc/nginx/queue_count:rw
      - ./examples/openresty/bsp_demo.lua:/usr/local/openresty/lualib/bsp_demo.lua
      - ./lib/opentelemetry:/usr/local/openresty/lualib/opentelemetry
    depends_on:
      - http-echo
    networks:
      - opentelemetry-lua
    ports:
      - 80:80
  http-echo:
    image: mendhak/http-https-echo:30
    networks:
      - opentelemetry-lua
    ports:
      - 8080:8080
    environment:
      - LOG_IGNORE_PATH=/demo
networks:
  opentelemetry-lua:
